# Generated by Django 3.0.4 on 2020-07-26 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('description', models.CharField(default='Add Profile Description', max_length=200)),
                ('phone', models.CharField(default='Add Phone Number', max_length=20)),
                ('firstSkill', models.CharField(default='Add First Skill', max_length=200)),
                ('secondSkill', models.CharField(default='Add Second Skill', max_length=200)),
                ('thirdSkill', models.CharField(default='Add Third Skill', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
