# Generated by Django 3.0.4 on 2020-08-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsapp',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='phone',
            field=models.CharField(default='add phone number', max_length=20),
        ),
    ]
