# Generated by Django 3.0.4 on 2020-07-26 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currentreading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sensorval', models.CharField(max_length=100)),
                ('date_recieved', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
