# Generated by Django 3.0.4 on 2020-07-28 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0002_currentreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='newsdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
