# Generated by Django 3.0.4 on 2020-07-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0003_auto_20200728_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='newsdate',
            field=models.CharField(max_length=300),
        ),
    ]
