# Generated by Django 3.0.4 on 2020-08-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0005_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentreading',
            options={'ordering': ['name']},
        ),
    ]
