# Generated by Django 3.0.4 on 2020-08-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0006_auto_20200806_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentreading',
            options={'ordering': ['last_update']},
        ),
    ]
