# Generated by Django 3.0.4 on 2020-08-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0007_auto_20200806_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['title']},
        ),
    ]
