# Generated by Django 3.0.4 on 2020-08-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0009_auto_20200806_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
