# Generated by Django 3.0.4 on 2020-08-06 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0010_auto_20200806_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='link',
            new_name='url',
        ),
    ]
