# Generated by Django 3.0.4 on 2020-08-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0011_auto_20200806_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='url',
            new_name='link',
        ),
    ]
