# Generated by Django 3.0.4 on 2020-08-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0012_auto_20200806_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='link',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
