# Generated by Django 3.0.4 on 2020-08-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0013_auto_20200806_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={},
        ),
    ]
