# Generated by Django 3.0.4 on 2020-08-26 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('innogrApp', '0014_auto_20200818_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=200)),
                ('temp', models.CharField(max_length=250)),
                ('hum', models.CharField(max_length=250)),
                ('windsp', models.CharField(max_length=250)),
                ('maindes', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=250)),
                ('date_recieved', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
